### ISSUE TITLE
Used this code in a project, question about attribution

### ISSUE THREAD

**Issue by DarthHater** [keithamus/parse-packagejson-name#13]
Hi there!

I inherited this dependency in a project I'm working on, and unfortunately I had to remove the dependency itself (policy related to age), but I DID use your code (converted to TypeScript, minimal niceties around that).

What I am wondering about is how to attribute you on the project!

https://github.com/sonatype-nexus-community/auditjs/pull/165/files#diff-024d8996a0ad9962991be97697a806f9R303-R328

That is where I have implemented it. Should I add you as a Copyright holder to the Apache license above?

Cheers!

**Comment by keithamus** [comment]
Hey @DarthHater! Thanks for taking the time to ask!

The "proper" answer would be that yes, you must copy the MIT notice into the code which you copy pasted, even if it was derivative. As the license states: 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

But I don't really care, it doesn't matter to me. I'm glad you made use of the library! For the purposes of AuditJS I am happy to waive copyright of said code, and require no attribution.
